Add friends likes
sgumail/java-filmorate pull request #3
Opened 2022-05-29 19:42 UTC by sgumail

Привет :)

Постарался сделать всё, что требовалось в ТЗ. Проверь пожалуйста!
ErrorHandler использовал по минимуму - не совсем разобрался как он отрабатывает и чем проще использованных мною @ResponseStatus в перехватчиках исключений. Вернее скорее не понял как внедрить его, например, для проверки e-mail на соответствие, если проверка идет через валидацию.

2022-05-29 20:43 UTC, sgumail commented
Пришлось отключить SPRING_PROFILES_ACTIVE для прохождения тестов на GitHUB :|

2022-05-30 05:08 UTC, eugene-lenkevich requested changes
Привет, Андрей, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-05-30 05:08 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage;
Контроллер все же пусть зависит только от сервиса, а вот сервис зависит от хранилища (storage), тогда у нас будут слои: уровень контроллера, уровень бизнес-логики и уровень хранилища данных. Иначе у нас контроллер оказывается жестко связанным с деталями реализации нижележащих слоев. 
В общем, давай связь с storage отсюда уберем и будем к нему обращаться через методы сервиса  :)

2022-05-30 05:08 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectFilmRealiseDateException.java
> +public class IncorrectFilmRealiseDateException extends RuntimeException {
А необходимо ли тут непроверяемое исключение?
Дата фильма задана неверна - вполне себе штатная ситуация, пусть тут будет проверяемое исключение :)
extends Exception

2022-05-30 05:08 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return Optional.of(userStorage.get(otherUserId).get().getFriends().stream()
А зачем тут Optional, его лучше использовать когда у нас передается единичный объект, в случае коллекции проще просто вернуть пустой список :)

2022-05-30 05:11 UTC, eugene-lenkevich commented
> ErrorHandler использовал по минимуму - не совсем разобрался как он отрабатывает и чем проще использованных мною @ResponseStatus в перехватчиках исключений. Вернее скорее не понял как внедрить его, например, для проверки e-mail на соответствие, если проверка идет через валидацию.

На самом деле сделанного вполне достаточно :)
А на счет валидации может поможет вот это 

https://stackoverflow.com/questions/12146298/spring-mvc-how-to-perform-validation
или же
https://habr.com/ru/company/haulmont/blog/427543/

2022-05-30 17:42 UTC, sgumail commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return Optional.of(userStorage.get(otherUserId).get().getFriends().stream()
а, ведь, и вправду ))

2022-05-30 17:44 UTC, sgumail commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectFilmRealiseDateException.java
> +public class IncorrectFilmRealiseDateException extends RuntimeException {
Это скорее всего по запарке - они все наследуются у меня от ValidationException, а он в свою очередь как раз от Exception.

2022-05-30 17:48 UTC, sgumail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage;
Расслоение и вправду вещь полезная. За образец написания брал Котограм, а там не дошло дело то отдельного сервиса хранения как у нас, поэтому, дабы не дублировать код, всё было закинуто в @RestController :|
Для UserService тоже сразу переделал.

2022-05-30 19:05 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-06-13 11:31 UTC, merged